name: mpflutter_wechat_api
description: The MPFlutter wechat miniprogram api.
version: 2.2.3
homepage: https://mpflutter.com/

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ">=2.0.0"