name: mpflutter_wechat_api_minigame
description: The MPFlutter wechat minigame api.
version: 2.1.0
homepage: https://mpflutter.com/

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ">=2.0.0"