name: mpflutter_wechat_api
description: The MPFlutter wechat miniprogram api.
publish_to: none
version: 2.0.0-alpha.4
homepage: /

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ">=2.0.0-alpha.4"